import http from "node:http";
import { randomBytes, randomUUID, scryptSync, timingSafeEqual } from "node:crypto";
import Redis from "ioredis";
import { WebSocketServer } from "ws";

const PORT = Number(process.env.PORT || 10000);
const OFFLINE_MESSAGE_TTL_SECONDS = 90 * 24 * 60 * 60;
const HISTORY_TTL_SECONDS = Number(process.env.HISTORY_TTL_SECONDS || 0);
const SESSION_TTL_SECONDS = 30 * 24 * 60 * 60;
const ADMIN_RESET_TTL_SECONDS = 30 * 60;
const ADMIN_AUDIT_LIMIT = 500;
const SAFETY_LOG_LIMIT = 1000;
const MAX_OFFLINE_MESSAGES_PER_USER = 500;
const MAX_HISTORY_MESSAGES_PER_USER = Number(process.env.MAX_HISTORY_MESSAGES_PER_USER || 0);
const DEFAULT_HISTORY_SYNC_LIMIT = Number(process.env.DEFAULT_HISTORY_SYNC_LIMIT || 300);
const MAX_HISTORY_SYNC_LIMIT = Number(process.env.MAX_HISTORY_SYNC_LIMIT || 5000);
const MAX_PROFILE_PICTURE_CHARS = 18000;
const MAX_UPSTASH_RPUSH_ITEMS = 4;
const MAX_UPSTASH_RPUSH_CHARS = 6_000_000;
const MAX_UPSTASH_COMMAND_CHARS = 8_500_000;
const MAX_QUEUED_ENVELOPE_CHARS = 7_500_000;
const MAX_WEBSOCKET_PAYLOAD_CHARS = 8_500_000;
const MAX_HISTORY_BATCH_CHARS = 240_000;
const OFFLINE_DELIVERY_BATCH_SIZE = 6;
const BACKGROUND_DELIVERY_YIELD_MS = 8;
const MAX_CALL_SIGNAL_CHARS = 64_000;
const MAX_GROUP_CALL_MEMBERS = 5;
const GROUP_CALL_TTL_MS = 4 * 60 * 60 * 1000;
const STORY_TTL_SECONDS = 24 * 60 * 60;
const REEL_TTL_SECONDS = Math.max(7 * 24 * 60 * 60, Number(process.env.REEL_TTL_SECONDS || 365 * 24 * 60 * 60));
